discord_token: MTA0ODc2MzYxMTY4Nzk0ODQyMQ.G5GQPT.Sa36b6YCF8ozP4KSd5_kEqFeK0D52WniUcCbwE
directory: '/home/michael/gigabot'

owner_id: 193534159212249090

openweathermapapi: 86c3033087b13f2901cddf6bdffb2003

reddit:
  client_id: j5lNZ7esbkZ1YLvwyykmYA
  client_secret: bkpQivfouvGsqofCKST8ZhNgsIkAtA
  user_agent: USER_AGENT
  username: B_33K
  password: Redditilssgdm1134957